image: docker:20.10.16

default:
  tags:
    - infrastructure

services:
  - docker:20.10.16-dind

variables:
  DOCKER_DRIVER: overlay

before_script:
  - docker info

build:
  stage: build
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD $REGISTRY
  script:
    - docker build -t $REGISTRY_USER/$CI_PROJECT_NAME:latest --network=host .
    - docker push $REGISTRY_USER/$CI_PROJECT_NAME:latest
